name: open_gpt_client
description: An open-source client to connect with OpenAI API's.

publish_to: 'none' 

version: 0.1.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.1
  file_picker: ^5.2.11
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.5
  http: ^0.13.5
  intl: any
  markdown_widget: ^2.1.0
  password_strength_checker: ^1.2.2
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0
  smooth_page_indicator: ^1.0.1
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/
    - assets/img/
    - .env

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/img/logo.png"
  web:
    generate: false
  windows:
    generate: true
  macos:
    generate: true